import { Inter } from "next/font/google";
import "./globals.css";
import Header from '@/components/shared/navbar/Header'
import Footer from "@/components/ui/Footer";
import Provider from "@/config/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tour Guide",
  description: "Generated by Team Typhon.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
         <Header />
          <div className="min-h-screen max-w-screen-xl mx-auto p-2">
            {children}
          </div>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
