import { Inter } from "next/font/google";
import "./globals.css";
// import Provider from "@/config/context";
import Footer from "@/components/shared/footer/Footer";
import Header from "@/components/shared/navbar/Header";
import AuthProvider from "@/config/context";
import Toaster from "@/components/ui/toaster"


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tour Guide",
  description: "Generated by Team Typhon.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <AuthProvider>
            <Header />
            <div>{children}</div>
            <Footer />
            <Toaster />
          </AuthProvider>
        </main>
      </body>
    </html>
  );
}
